# Generated by Django 4.2.7 on 2024-10-06 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(1, 'Действует'), (2, 'Удалена')], default=1)),
                ('date_created', models.DateTimeField()),
                ('submitted', models.DateTimeField()),
                ('completed', models.DateTimeField()),
                ('vacancy', models.JSONField(blank=True, default=dict)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_applications', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'applications',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('population', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=10)),
                ('unemployment_rate', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=300)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'cities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CitiesApplications',
            fields=[
                ('mm_id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('app_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.applications')),
                ('city_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.cities')),
            ],
            options={
                'db_table': 'cities_applications',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='citiesapplications',
            constraint=models.UniqueConstraint(fields=('city_id', 'app_id'), name='unique constraint'),
        ),
    ]
