# Generated by Django 4.2.7 on 2024-12-30 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancyapplications',
            name='duration_days',
        ),
    ]
