# Generated by Django 4.2.7 on 2024-10-17 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('population', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=10)),
                ('unemployment_rate', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Действует'), (2, 'Удалена')], default=1)),
            ],
            options={
                'db_table': 'cities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VacancyApplications',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(1, 'Черновик'), (2, 'Удалена'), (3, 'Сформирована'), (4, 'Завершена'), (5, 'Отклонена')], default=1)),
                ('date_created', models.DateTimeField()),
                ('submitted', models.DateTimeField(blank=True, null=True)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('vacancy_name', models.TextField(blank=True, null=True)),
                ('vacancy_responsibilities', models.TextField(blank=True, null=True)),
                ('vacancy_requirements', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_applications', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vacancy_applications',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CitiesVacancyApplications',
            fields=[
                ('mm_id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=1)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.vacancyapplications')),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.cities')),
            ],
            options={
                'db_table': 'cities_vacancy_applications',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='citiesvacancyapplications',
            constraint=models.UniqueConstraint(fields=('city_id', 'app_id'), name='unique constraint'),
        ),
    ]
