# Generated by Django 4.2.7 on 2024-12-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_vacancyapplications_duration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyapplications',
            name='duration_days',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
