# Generated by Django 4.2.7 on 2024-12-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_vacancyapplications_duration_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyapplications',
            name='duration_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
