# Generated by Django 4.2.7 on 2024-10-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_applications_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
