# Generated by Django 5.1 on 2024-10-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_cities_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
