# Generated by Django 4.2.7 on 2024-10-16 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_alter_applications_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='vacancy',
        ),
        migrations.AddField(
            model_name='applications',
            name='vacancy_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applications',
            name='vacancy_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applications',
            name='vacancy_responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.IntegerField(choices=[(1, 'Черновик'), (2, 'Удалена'), (3, 'Сформирована'), (4, 'Завершена'), (5, 'Отклонена')], default=1),
        ),
        migrations.AlterField(
            model_name='citiesapplications',
            name='count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
