# Generated by Django 4.2.7 on 2024-10-16 20:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_remove_applications_vacancy_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CitiesApplications',
            new_name='CitiesVacancyApplications',
        ),
        migrations.RenameModel(
            old_name='Applications',
            new_name='VacancyApplications',
        ),
        migrations.AlterModelTable(
            name='citiesvacancyapplications',
            table='cities_vacancy_applications',
        ),
        migrations.AlterModelTable(
            name='vacancyapplications',
            table='vacancy_applications',
        ),
    ]
