# Generated by Django 4.2.7 on 2024-10-17 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_citiesapplications_citiesvacancyapplications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citiesvacancyapplications',
            name='app_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.vacancyapplications'),
        ),
        migrations.AlterField(
            model_name='citiesvacancyapplications',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.cities'),
        ),
        migrations.AlterField(
            model_name='citiesvacancyapplications',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
